### PR TITLE
test with php 5.3 too

### PR DESCRIPTION
**Pull request by marcioAlmada**
because https://github.com/phpbrew/phpbrew/issues/513

### CODE REVIEW

**Comment by marcioAlmada** [comment]
ping @c9s:

```
PHP Parse error:  syntax error, unexpected '[' in phar:///usr/local/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2
```

:scream_cat:

**Comment by c9s** [comment]
epic fail.....

**Comment by marcioAlmada** [comment]
there is still some files with 5.4 syntax within the underneath *codegen* package, but they don't break phpbrew AFAIK.

**Comment by c9s** [comment]
ok i will roll out a patch release

**Pull request merged**
